# The unique identifier of the application.
name: app

# The language that will run your application.
type: php:7.0

# The way to build your application.
build:
    flavor: drupal

# The way services are mapped within your application.
relationships:
    database: "database:mysql"
    # solr: "solr:solr"
    # redis: "redis:redis"

# The way your application is exposed to the web.
web:
    locations:
        '/':
            # The folder from which to serve static assets, for this location.
            #
            # This is a filesystem path, relative to the application root.
            root: 'public'

            # How long to allow static assets from this location to be cached.
            #
            # Can be a time in seconds, or -1 for no caching. Times can be
            # suffixed with "s" (seconds), "m" (minutes), "h" (hours), "d"
            # (days), "w" (weeks), "M" (months, as 30 days) or "y" (years, as
            # 365 days).
            expires: 5m

            # Whether to forward disallowed and missing resources from this
            # location to the application.
            #
            # Can be true, false or a URI path string.
            passthru: '/index.php'

            # Deny access to static files in this location.
            allow: false

            # Rules for specific URI patterns.
            rules:
                # Allow access to common static files.
                '\.(jpe?g|png|gif|svgz?|css|js|map|ico|bmp|eot|woff2?|otf|ttf)$':
                    allow: true
                '^/robots\.txt$':
                    allow: true
                '^/sitemap\.xml$':
                    allow: true

        '/sites/default/files':
            # Allow access to all files in the public files directory.
            allow: true
            expires: 5m
            passthru: '/index.php'
            root: 'public/sites/default/files'

            # Do not execute PHP scripts.
            scripts: false

            rules:
                # Provide a longer TTL (2 weeks) for aggregated CSS and JS files.
                '^/sites/default/files/(css|js)':
                    expires: 2w

# The size of the persistent disk size of your application in MB.
disk: 2048

# The volumes that are mounted under a writable shared resource.
mounts:
    "/public/sites/default/files": "shared:files/files"
    "/tmp": "shared:files/tmp"
    "/private": "shared:files/private"
    "/drush-backups": "shared:files/drush-backups"

# The shell commands to run during the build or deployment process.
hooks:
    # We run deploy hook after your application has been deployed and started.
    deploy: |
        cd public
        drush -y updatedb
        drush composer-json-rebuild
        cd sites/default/files/composer
        composer -n install

# The processes that are triggered on a schedule.
crons:
    drupal:
        spec: "*/20 * * * *"
        cmd: "cd public ; drush core-cron"
